name: Q1 - Archive TOTO.txt

on:
  workflow_dispatch:

jobs:
  archive:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4
        with:
          clean: true
      
      - name: Configurer Git
        run: |
          git config user.name "FCiraci"
          git config user.email "furkan.ciraci@icloud.com"
      
      - name: Synchroniser avec le dépôt distant
        run: |
          git fetch origin main
          git reset --hard origin/main
      
      - name: Créer Q1_archive_TOTO.txt
        run: |
          cp TOTO.txt Q1_archive_TOTO.txt
      
      - name: Commit et push
        run: |
          git add Q1_archive_TOTO.txt
          git commit -m "Q1: Archivage de TOTO.txt"
          git push
