name: Q1 - Archive TOTO.txt

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'TOTO.txt'

jobs:
  archive:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4
        with:
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configurer Git
        run: |
          git config user.name "FCiraci"
          git config user.email "furkan.ciraci@icloud.com"
      
      - name: Synchroniser avec le dépôt distant
        run: |
          git fetch origin main
          git reset --hard origin/main
      
      - name: Créer Q1_archive_TOTO.txt
        run: |
          cp TOTO.txt Q1_archive_TOTO.txt
      
      - name: Commit et push
        run: |
          git add Q1_archive_TOTO.txt
          
          # Vérifier s'il y a des changements
          if git diff --staged --quiet; then
            echo "Aucun changement à commiter"
            exit 0
          fi
          
          git commit -m "Q1: Archivage de TOTO.txt"
          
          # Push avec retry
          max_attempts=3
          attempt=1
          until git push origin main; do
            if [ $attempt -ge $max_attempts ]; then
              echo "Échec après $max_attempts tentatives"
              exit 1
            fi
            echo "Push rejeté, tentative $attempt/$max_attempts..."
            git pull --rebase origin main
            attempt=$((attempt + 1))
          done
