name: Q2 - Archive README.md avec métadonnées

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  archive:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configurer Git
        run: |
          git config user.name "FCiraci"
          git config user.email "furkan.ciraci@icloud.com"
      
      - name: Synchroniser avec le dépôt distant
        run: |
          git fetch origin main
          git reset --hard origin/main
      
      - name: Créer Q2_archive_README.txt avec métadonnées
        run: |
          # Créer le fichier avec les métadonnées
          echo "Nom et prénom: Furkan Ciraci" > Q2_archive_README.txt
          echo "Date et heure d'exécution: $(date '+%Y-%m-%d %H:%M:%S')" >> Q2_archive_README.txt
          echo "" >> Q2_archive_README.txt
          echo "=== Contenu de README.md ===" >> Q2_archive_README.txt
          cat README.md >> Q2_archive_README.txt
          echo "" >> Q2_archive_README.txt
          echo "=== Informations ===" >> Q2_archive_README.txt
          echo "Taille de README.md: $(wc -c < README.md) octets" >> Q2_archive_README.txt
      
      - name: Commit et push
        run: |
          git add Q2_archive_README.txt
          
          # Vérifier s'il y a des changements
          if git diff --staged --quiet; then
            echo "Aucun changement à commiter"
            exit 0
          fi
          
          git commit -m "Q2: Archivage de README.md avec métadonnées"
          
          # Push avec retry
          max_attempts=3
          attempt=1
          until git push origin main; do
            if [ $attempt -ge $max_attempts ]; then
              echo "Échec après $max_attempts tentatives"
              exit 1
            fi
            echo "Push rejeté, tentative $attempt/$max_attempts..."
            git pull --rebase origin main
            attempt=$((attempt + 1))
          done
